In the cell below we handled text preprocessing using hazm.

Performance Note: This preprocessing step is computationally intensive and may take 20-30 minutes to complete.

Reason: The hazm library utilizes an extensive set of Regular Expression rules to standardize Persian orthography (e.g., correcting spacing for prefixes/suffixes and unifying Unicode characters). This process is applied sequentially to ensure high-precision tokenization.

In [7]:
import pandas as pd
from hazm import Normalizer, word_tokenize, stopwords_list
from tqdm import tqdm

tqdm.pandas(bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]')

df = pd.read_csv('../data/processed/clean_data.csv')

normalizer = Normalizer()
stop_words = set(stopwords_list())

def preprocess_step_1(text):
    if not isinstance(text, str): return []
    try:
        # 1. Normalize
        text = normalizer.normalize(text)
        # 2. Tokenize
        tokens = word_tokenize(text)
        # 3. Stopword Removal
        clean_tokens = [t for t in tokens if t not in stop_words]
        return clean_tokens
    except:
        return []

print("Running Preprocessing ...")

df['clean_tokens_list'] = df['comment_text'].progress_apply(preprocess_step_1)

print("Process Complete.")
print(df[['comment_text', 'clean_tokens_list']].head(2))

Running Preprocessing ...

100%|██████████| 4548/4548 [33:50<00:00]

Process Complete.
                                        comment_text  \
0                                چیزی اضافه ایی نیست
1  خوب درس نمیده اصلا، نمره ها رو خوب نمیده و اصل...

                                   clean_tokens_list
0                                       [اضافه, ایی]
1  [درس, نمیده, اصلا, ،, نمره‌ها, نمیده, اصلا, تر...

In the cell below we use a simple lexicon-based approach, what it does is we set some positive and negative words and then use them to handle training. Although it is simple it lacks understanding meaning sentences with sarcasm won't be noticed.

In [8]:
positive_keywords = {
    'خوب', 'عالی', 'بهترین', 'راضی', 'مفید', 'مهربان', 
    'با‌سواد', 'محترم', 'قوی', 'منصف', '۲۰', '20', 'تشکر',
    'استاد نمونه', 'خوش برخورد', 'مسلط'
}

negative_keywords = {
    'بد', 'ضعیف', 'بی‌کیفیت', 'افتضاح', 'حیف', 'بی‌سواد', 
    'نامرد', 'سخت‌گیر', 'بی‌مسئولیت', 'خسته', 'الکی', 'نمی‌دهد',
    'عقده ای', 'پاس نمیکنه', 'میندازه', 'نمره نمیده'
}

def get_simple_sentiment(tokens):
    score = 0
    if not isinstance(tokens, list): return 'Neutral', 0
    
    for token in tokens:
        if token in positive_keywords:
            score += 1
        elif token in negative_keywords:
            score -= 1
            
    if score > 0:
        label = 'Positive'
    elif score < 0:
        label = 'Negative'
    else:
        label = 'Neutral'
        
    return label, score


df[['simple_label', 'simple_score']] = df['clean_tokens_list'].progress_apply(
    lambda x: pd.Series(get_simple_sentiment(x))
)

print("Process Complete.")
print("Distribution of Simple Labels:")
print(df['simple_label'].value_counts())

100%|██████████| 4548/4548 [00:00<00:00]

Process Complete.
Distribution of Simple Labels:
simple_label
Neutral     3703
Positive     483
Negative     362
Name: count, dtype: int64

We use ParsBERT in the cell below. Since it is trained on Dijikala data beforehand, our job is simple, give it the data and wait for it to finish.

Important Note: I disabled torch from checking out my model that I put in the folders, it is a security check which isn't bad to keep but I didn't do so because of an error. To activate this security feature you can comment line 26 of the code below (I meant this line: weights_only=False).

In [9]:
import os
from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer
from tqdm import tqdm
import torch

HUB_MODEL_ID = "HooshvareLab/bert-fa-base-uncased-sentiment-digikala"
LOCAL_MODEL_PATH = "../models/parsbert_sentiment"

def load_sentiment_pipeline():
    abs_path = os.path.abspath(LOCAL_MODEL_PATH)

    if not os.path.exists(abs_path):
        os.makedirs(abs_path, exist_ok=True)

    if os.listdir(abs_path):
        print(f"Found local model at '{abs_path}'. Loading from disk...")
        model_source = abs_path
    else:
        print(f"Local model not found. Downloading from Hugging Face (~450MB)...")
        model_source = HUB_MODEL_ID

    tokenizer = AutoTokenizer.from_pretrained(model_source)

    model = AutoModelForSequenceClassification.from_pretrained(
        model_source, 
        weights_only=False 
    )

    if model_source == HUB_MODEL_ID:
        print(f"Saving model to '{abs_path}'...")
        tokenizer.save_pretrained(abs_path)
        model.save_pretrained(abs_path)
        print("Model saved successfully.")

    return pipeline("text-classification", model=model, tokenizer=tokenizer)


sentiment_pipeline = load_sentiment_pipeline()

def get_bert_sentiment(text):
    if not isinstance(text, str) or len(text.strip()) < 2:
        return "Neutral", 0.0

    safe_text = text[:1000]

    try:
        result = sentiment_pipeline(safe_text, truncation=True, max_length=512)[0]
        label = result['label']
        score = result['score']

        if label == 'recommended':
            return 'Positive', score
        elif label == 'not_recommended':
            return 'Negative', -score
        elif label == 'no_idea':
            return 'Neutral', 0
        else:
            return label, score
    except:
        return "Error", 0

tqdm.pandas(desc="Running ParsBERT")
print("Running AI on 4,500 rows ...")

df[['bert_label', 'bert_score']] = df['clean_comment_text'].progress_apply(
    lambda x: pd.Series(get_bert_sentiment(x))
)

print("Process Complete!")
display(df[['clean_comment_text', 'simple_label', 'bert_label']].head(10))

Found local model at 'F:\Programming\DataMiningProject\models\parsbert_sentiment'. Loading from disk...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: F:\Programming\DataMiningProject\models\parsbert_sentiment
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Running AI on 4,500 rows ...

Running ParsBERT: 100%|██████████| 4548/4548 [05:45<00:00, 13.17it/s]

Process Complete!

                                  clean_comment_text simple_label bert_label
0                                چیزی اضافه ایی نیست      Neutral   Negative
1  خوب درس نمیده اصلا، نمره ها رو خوب نمیده و اصل...      Neutral   Negative
2  در کل اگر که دنبال یک استاد با ادب با دانشجو م...      Neutral   Positive
3                                  سخت گیر و پربازده     Negative   Positive
4                                چیزی اضافه ایی نیست      Neutral   Negative
5  دقت کنید هر جلسه مطالب را بخونید ارشد شب امتحا...      Neutral   Positive
6                                چیزی اضافه ایی نیست      Neutral   Negative
7  اعصابی براتون نمیمونه چه نمره خوبی بگیرید چه ب...      Neutral    Neutral
8  استاد خوبی هستند فقط امتحان های سختی میگیرن که...      Neutral   Positive
9             سعی کنید سر کلاس خوب گوش بدید به مطالب      Neutral   Positive

As every good notebook with multiple methods go we have to compare the two models and their results. You can clearly see how much better ParsBERT does. It catches sarcasm and things in this nature. See this line here:

3                                  سخت گیر و پربازده     Negative   Positive

This line shows exactly how ParsBERT works better because it figured out correctly that this is a positive comment not a negative one. But lets see another example that showcases why it is not the best idea to use it for comments describing professors:

چیزی اضافه ایی نیست,Neutral,Negative

Funny thing is ParsBERT found this to be negative when in reality it is neutral. You might think why, the reason is because of its initial training on Dijikala data! In Dijikala when a user answered چیزی نیست for what are the advantages, this is a negative response and this model learned it from there and carried it over here. This shows that this model isn't perfect either.

In [10]:
print("Comparison of Methods:")
print(df[['clean_comment_text', 'simple_label', 'bert_label']].head(10))

mask_improved = (df['simple_label'] == 'Neutral') & (df['bert_label'] != 'Neutral')

print(f"\nInsight: The AI found sentiment in {mask_improved.sum()} rows that the Simple Method missed!")

print("\n--- Examples where AI was smarter ---")
display(df.loc[mask_improved, ['clean_comment_text', 'simple_label', 'bert_label']].head(5))

Comparison of Methods:
                                  clean_comment_text simple_label bert_label
0                                چیزی اضافه ایی نیست      Neutral   Negative
1  خوب درس نمیده اصلا، نمره ها رو خوب نمیده و اصل...      Neutral   Negative
2  در کل اگر که دنبال یک استاد با ادب با دانشجو م...      Neutral   Positive
3                                  سخت گیر و پربازده     Negative   Positive
4                                چیزی اضافه ایی نیست      Neutral   Negative
5  دقت کنید هر جلسه مطالب را بخونید ارشد شب امتحا...      Neutral   Positive
6                                چیزی اضافه ایی نیست      Neutral   Negative
7  اعصابی براتون نمیمونه چه نمره خوبی بگیرید چه ب...      Neutral    Neutral
8  استاد خوبی هستند فقط امتحان های سختی میگیرن که...      Neutral   Positive
9             سعی کنید سر کلاس خوب گوش بدید به مطالب      Neutral   Positive

Insight: The AI found sentiment in 2837 rows that the Simple Method missed!

--- Examples where AI was smarter ---

                                  clean_comment_text simple_label bert_label
0                                چیزی اضافه ایی نیست      Neutral   Negative
1  خوب درس نمیده اصلا، نمره ها رو خوب نمیده و اصل...      Neutral   Negative
2  در کل اگر که دنبال یک استاد با ادب با دانشجو م...      Neutral   Positive
4                                چیزی اضافه ایی نیست      Neutral   Negative
5  دقت کنید هر جلسه مطالب را بخونید ارشد شب امتحا...      Neutral   Positive

In [6]:
output_path = '../data/processed/sentiment_data.csv'

print(f"Saving sentiment results to '{output_path}'...")
df.to_csv(output_path, index=False)

print("Data saved safely.")
print(f"Total Rows: {len(df)}")

Saving sentiment results to '../data/processed/sentiment_data.csv'...
Data saved safely.
Total Rows: 4548